# Generated by Django 3.0.3 on 2020-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_active',
            field=models.BooleanField(default=False),
        ),
    ]
