# Generated by Django 3.0.3 on 2020-11-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20201108_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='userdetails_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='userdetails_position',
            new_name='position',
        ),
    ]
