# Generated by Django 3.0.3 on 2020-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_company_has_usersdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_has_usersdetails',
            name='company',
        ),
    ]
