# Generated by Django 3.0.3 on 2020-11-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_remove_company_has_usersdetails_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_has_usersdetails',
            name='comapny_has_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Api.Company_has_users'),
        ),
    ]
