# Generated by Django 3.0.3 on 2020-11-08 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_company_has_usersdetails_comapny_has_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('admin_username', models.CharField(max_length=100, unique=True)),
                ('admin_password', models.CharField(blank=True, max_length=80, null=True)),
                ('admin_is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Company')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='News_category',
            fields=[
                ('news_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_category_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'news_category',
            },
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userdetails_bd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(blank=True, max_length=180, null=True)),
                ('news_excerpt', models.CharField(blank=True, max_length=180, null=True)),
                ('news_body', models.TextField(blank=True)),
                ('news_image', models.CharField(blank=True, max_length=180, null=True)),
                ('created', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Admin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Company')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.News_category')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
