# Generated by Django 3.0.3 on 2020-11-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20201108_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_title', models.CharField(blank=True, max_length=180, null=True)),
                ('announcement_body', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Admin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Company')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
