# Generated by Django 3.0.3 on 2020-11-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_beacon_company_has_beacon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_has_users',
            old_name='comapny_has_users_id',
            new_name='company_has_users_id',
        ),
    ]
