# Generated by Django 3.0.3 on 2020-11-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20201117_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_has_beacon',
            old_name='comapany_has_beacon_id',
            new_name='company_has_beacon_id',
        ),
        migrations.RenameField(
            model_name='company_has_usersdetails',
            old_name='comapny_has_users',
            new_name='company_has_users',
        ),
    ]
