# Generated by Django 3.0.3 on 2020-12-05 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_auto_20201118_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_method',
            fields=[
                ('attendance_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_method_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'attendance_method',
            },
        ),
        migrations.CreateModel(
            name='Attendance_type',
            fields=[
                ('attendance_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_type_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'attendance_type',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('attendance_time', models.TimeField(blank=True, null=True)),
                ('attendace_remark', models.CharField(blank=True, max_length=150, null=True)),
                ('attendance_location', models.CharField(blank=True, max_length=150, null=True)),
                ('attendance_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_long', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Attendance_method')),
                ('attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Attendance_type')),
                ('users_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_uuid_attendance', to='Api.Users', to_field='users_uuid')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
