# Generated by Django 3.0.3 on 2020-12-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_attendance_attendance_method_attendance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('leave_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.Users', to_field='users_uuid')),
            ],
        ),
    ]
